// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMPXFGUKdTnOWeb-LrOSh0eFTUaoZKyJE',
    appId: '1:176912889439:web:bd52ed2255419ae5e7cdea',
    messagingSenderId: '176912889439',
    projectId: 'lifeline-61f28',
    authDomain: 'lifeline-61f28.firebaseapp.com',
    storageBucket: 'lifeline-61f28.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr_T13o1XMp_XMLKUwoA9WGtJhHiSStEo',
    appId: '1:176912889439:android:84732855c955af31e7cdea',
    messagingSenderId: '176912889439',
    projectId: 'lifeline-61f28',
    storageBucket: 'lifeline-61f28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeYXOptMMO8lSeIvcJt4JBfcFYlspwGvk',
    appId: '1:176912889439:ios:db8cf541cfaf388ce7cdea',
    messagingSenderId: '176912889439',
    projectId: 'lifeline-61f28',
    storageBucket: 'lifeline-61f28.firebasestorage.app',
    androidClientId: '176912889439-mc5qkr3ufddt9il3mnfdbvsqj4asf66k.apps.googleusercontent.com',
    iosClientId: '176912889439-ii4itia2vmnjq29m278aj3q2opmlu91s.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifeline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeYXOptMMO8lSeIvcJt4JBfcFYlspwGvk',
    appId: '1:176912889439:ios:db8cf541cfaf388ce7cdea',
    messagingSenderId: '176912889439',
    projectId: 'lifeline-61f28',
    storageBucket: 'lifeline-61f28.firebasestorage.app',
    androidClientId: '176912889439-mc5qkr3ufddt9il3mnfdbvsqj4asf66k.apps.googleusercontent.com',
    iosClientId: '176912889439-ii4itia2vmnjq29m278aj3q2opmlu91s.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifeline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMPXFGUKdTnOWeb-LrOSh0eFTUaoZKyJE',
    appId: '1:176912889439:web:4f1235a0741a0daee7cdea',
    messagingSenderId: '176912889439',
    projectId: 'lifeline-61f28',
    authDomain: 'lifeline-61f28.firebaseapp.com',
    storageBucket: 'lifeline-61f28.firebasestorage.app',
  );
}
